In [1]:
import numpy as np
import random

In [2]:
# 데이터불러오기
loaded_data = np.loadtxt('./shuffle_test.csv', delimiter=',', dtype=np.float32)

print("Before shuffle...")

print("\nloaded_data.shape = ", loaded_data.shape , ", loaded_data length = ", len(loaded_data)) 
print("\nloaded_data = ", loaded_data)

Before shuffle...

loaded_data.shape =  (4, 4) , loaded_data length =  4

loaded_data =  [[1. 2. 3. 1.]
 [6. 7. 8. 2.]
 [3. 4. 5. 6.]
 [0. 0. 1. 0.]]


In [3]:
# 데이터를 임의로 shuffle 
random.shuffle(loaded_data)

print("After shuffle...")

print("\nloaded_data.shape = ", loaded_data.shape , ", loaded_data length = ", len(loaded_data)) 
print("\nloaded_data = ", loaded_data)

After shuffle...

loaded_data.shape =  (4, 4) , loaded_data length =  4

loaded_data =  [[1. 2. 3. 1.]
 [1. 2. 3. 1.]
 [3. 4. 5. 6.]
 [3. 4. 5. 6.]]


In [4]:
# 분리 비율 40 %
seperation_rate = 0.4

random_data_count = int(len(loaded_data)*seperation_rate)

print("loaded_data = ", loaded_data, ", loaded_data length = ", len(loaded_data)) 

print("\nrandom_data_count = ", random_data_count)

loaded_data =  [18, 20, 15, 21, 17, 24, 19, 23, 16, 22] , loaded_data length =  10

random_data_count =  4


In [7]:
# slicing 을 이용하여 loaded_data 로 부터 training data 와 test data 분리

# test data 분리
test_data_list = loaded_data[ :random_data_count ]

print("test data list = ", test_data_list)

# training data 분리
training_data_list = loaded_data[ random_data_count: ]

print("\ntraining data list= ", training_data_list)

# loaded data 출력

print("\nloaded_data  = ", loaded_data)

test data list =  [18, 20, 15, 21]

training data list=  [17, 24, 19, 23, 16, 22]

loaded_data  =  [18, 20, 15, 21, 17, 24, 19, 23, 16, 22]


In [8]:
# 행렬계산을 위해 list 타입인 training data 와 test data 를 numpy 로 변환

training_data = np.array(training_data_list)

test_data = np.array(test_data_list)

print("training_data.shape = ", training_data.shape, ", test_data.shape = ", test_data.shape)

training_data.shape =  (6,) , test_data.shape =  (4,)
