## Class 를 이용하여 data-01.csv 선형회귀 구현
## 입력을 vector 받는 경우 테스트

In [1]:
import numpy as np
from datetime import datetime

class LinearRegressionTest:
    
    # constructor
    def __init__(self, xdata, tdata, learning_rate, iteration_count):
            
        # 가중치 W 형상을 자동으로 구하기 위해 입력데이터가 vector 인지,
        # 아니면 matrix 인지 체크 후, 
        # self.xdata 는 무조건 matrix 로 만들어 주면 코드 일관성이 있음
        
        if xdata.ndim == 1:    # vector
            self.xdata = xdata.reshape(len(xdata), 1)
            self.tdata = xdata.reshape(len(tdata), 1)
            
        elif xdata.ndim == 2:  # matrix
            self.xdata = xdata
            self.tdata = tdata
        
        self.learning_rate = learning_rate
        self.iteration_count = iteration_count
        
        self.W = np.random.rand(self.xdata.shape[1], 1) 
        self.b = np.random.rand(1)
        
        print("LinearRegressionTest Object is created")
        
    
    # obtain current W and current b
    def getW_b(self):
        
        return self.W, self.b
    
    
    # loss function
    def loss_func(self):
        
        y = np.dot(self.xdata, self.W) + self.b
    
        return ( np.sum( (self.tdata - y)**2 ) ) / ( len(self.xdata) )
        
    
    # display current error value
    def error_val(self):
        
        y = np.dot(self.xdata, self.W) + self.b
    
        return ( np.sum( (self.tdata - y)**2 ) ) / ( len(self.xdata) )
    
    
    # predict method
    def predict(self, test_data):
        
        y = np.dot(test_data, self.W) + self.b
        
        return y
    
    
    # train method
    def train(self):
    
        f = lambda x : self.loss_func()

        print("Initial error value = ", self.error_val(), "Initial W = ", self.W, "\n", ", b = ", self.b )

        start_time = datetime.now()
        
        for step in  range(self.iteration_count):  
    
            self.W -= self.learning_rate * numerical_derivative(f, self.W)
    
            self.b -= self.learning_rate * numerical_derivative(f, self.b)
    
            if (step % 400 == 0):
                print("step = ", step, "error value = ", self.error_val(), "W = ", self.W, ", b = ", self.b )
                
        end_time = datetime.now()
        
        print("")
        print("Elapsed Time => ", end_time - start_time)

In [2]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

In [3]:
loaded_data = np.loadtxt('./data-01.csv', delimiter=',', dtype=np.float32)

x_data = loaded_data[ :, 0:-1]
t_data = loaded_data[ :, [-1]]

# 데이터 차원 및 shape 확인
print("x_data.ndim = ", x_data.ndim, ", x_data.shape = ", x_data.shape)
print("t_data.ndim = ", t_data.ndim, ", t_data.shape = ", t_data.shape) 

x_data.ndim =  2 , x_data.shape =  (25, 3)
t_data.ndim =  2 , t_data.shape =  (25, 1)


### learning_rate = 1e-5,  반복횟수 10,000번 수행하는 obj1
### 입력 xdata 는 (25, 3) 행렬 데이터 타입

In [4]:
# 입력 xdata 는 (25, 3) 행렬 데이터 타입

obj1 = LinearRegressionTest(x_data, t_data, 1e-5, 10001)

obj1.train()

LinearRegressionTest Object is created
Initial error value =  7121.208477466941 Initial W =  [[0.1921415 ]
 [0.44467335]
 [0.33849799]] 
 , b =  [0.49370806]
step =  0 error value =  2640.642006564821 W =  [[0.32682412]
 [0.5800138 ]
 [0.47730795]] , b =  [0.49472253]
step =  400 error value =  10.434354388226932 W =  [[0.51733279]
 [0.74190752]
 [0.75756236]] , b =  [0.49602261]
step =  800 error value =  9.20887353150514 W =  [[0.50080785]
 [0.7020375 ]
 [0.81258776]] , b =  [0.49567713]
step =  1200 error value =  8.341914330560787 W =  [[0.48604672]
 [0.66915604]
 [0.85907042]] , b =  [0.49527187]
step =  1600 error value =  7.7276593371171804 W =  [[0.47285033]
 [0.64207768]
 [0.89836213]] , b =  [0.49481607]
step =  2000 error value =  7.291693205161807 W =  [[0.46104369]
 [0.61981456]
 [0.93159824]] , b =  [0.49431754]
step =  2400 error value =  6.981652624440568 W =  [[0.45047267]
 [0.60154379]
 [0.95973256]] , b =  [0.49378283]
step =  2800 error value =  6.760665976460043 W 

In [5]:
test_data = np.array([100, 98, 81])

obj1.predict(test_data) 

array([179.08177577])

### learning_rate = 1e-5,  반복횟수 10,000번 수행하는 obj2
### 입력 xdata 는 (10, 1) 벡터 데이터 타입

In [6]:
x_data = np.array([ data  for  data  in range(-10, 50) ])
t_data = np.array([ 2*data-1  for  data  in range(-10, 50) ])

print('x_data.shape = ', x_data.shape, ', t_data.shape = ', t_data.shape)

x_data.shape =  (60,) , t_data.shape =  (60,)


In [7]:
obj2 = LinearRegressionTest(x_data, t_data, 1e-5, 80001)

obj2.train()

LinearRegressionTest Object is created
Initial error value =  556.2746886759973 Initial W =  [[0.09520812]] 
 , b =  [0.01538423]
step =  0 error value =  541.2311566642445 W =  [[0.10751031]] , b =  [0.01573199]
step =  400 error value =  0.010083573993067946 W =  [[0.99512477]] , b =  [0.04070529]
step =  800 error value =  0.0007293836391232514 W =  [[0.99881796]] , b =  [0.04066609]
step =  1200 error value =  0.00072409939796308 W =  [[0.9988374]] , b =  [0.04052344]
step =  1600 error value =  0.0007190128447764968 W =  [[0.99884155]] , b =  [0.04038086]
step =  2000 error value =  0.0007139620265275561 W =  [[0.99884563]] , b =  [0.04023878]
step =  2400 error value =  0.000708946688545523 W =  [[0.99884969]] , b =  [0.0400972]
step =  2800 error value =  0.0007039665815899815 W =  [[0.99885374]] , b =  [0.03995612]
step =  3200 error value =  0.0006990214581750865 W =  [[0.99885777]] , b =  [0.03981553]
step =  3600 error value =  0.0006941110725534556 W =  [[0.99886179]] , b =

In [8]:
test_data = np.array([100])

obj2.predict(test_data) 

array([99.96218113])

In [10]:
test_data = np.array([777])

obj2.predict(test_data) 

array([776.56914319])

In [11]:
test_data = np.array([-45])

obj2.predict(test_data) 

array([-44.95363793])