## Class 를 이용하여 data-01.csv 선형회귀 구현
## 멀티 오브젝트를 통한 테스트 다양성 시도 (reset 불필요)

In [1]:
import numpy as np
from datetime import datetime

class LinearRegressionTest:
    
    # constructor
    def __init__(self, xdata, tdata, learning_rate, iteration_count):            
        
        self.learning_rate = learning_rate
        self.iteration_count = iteration_count
        
        self.W = np.random.rand(self.xdata.shape[1], 1) # 입력 xdata가 이미 행렬이라 가정한 구현
        self.b = np.random.rand(1)
        
        print("LinearRegressionTest Object is created")
        
    
    # obtain current W and current b
    def getW_b(self):
        
        return self.W, self.b
    
    
    # loss function
    def loss_func(self):
        
        y = np.dot(self.xdata, self.W) + self.b
    
        return ( np.sum( (self.tdata - y)**2 ) ) / ( len(self.xdata) )
        
    
    # display current error value
    def error_val(self):
        
        y = np.dot(self.xdata, self.W) + self.b
    
        return ( np.sum( (self.tdata - y)**2 ) ) / ( len(self.xdata) )
    
    
    # predict method
    def predict(self, test_data):
        
        y = np.dot(test_data, self.W) + self.b
        
        return y
    
    
    # train method
    def train(self):
    
        f = lambda x : self.loss_func()

        print("Initial error value = ", self.error_val(), "Initial W = ", self.W, "\n", ", b = ", self.b )

        start_time = datetime.now()
        
        for step in  range(self.iteration_count):  
    
            self.W -= self.learning_rate * numerical_derivative(f, self.W)
    
            self.b -= self.learning_rate * numerical_derivative(f, self.b)
    
            if (step % 400 == 0):
                print("step = ", step, "error value = ", self.error_val(), "W = ", self.W, ", b = ", self.b )
                
        end_time = datetime.now()
        
        print("")
        print("Elapsed Time => ", end_time - start_time)

In [2]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

In [3]:
loaded_data = np.loadtxt('./data-01.csv', delimiter=',', dtype=np.float32)

x_data = loaded_data[ :, 0:-1]
t_data = loaded_data[ :, [-1]]

# 데이터 차원 및 shape 확인
print("x_data.ndim = ", x_data.ndim, ", x_data.shape = ", x_data.shape)
print("t_data.ndim = ", t_data.ndim, ", t_data.shape = ", t_data.shape) 

x_data.ndim =  2 , x_data.shape =  (25, 3)
t_data.ndim =  2 , t_data.shape =  (25, 1)


### learning_rate = 1e-5,  반복횟수 10,000번 수행하는 obj1

In [4]:
# LinearRegressionTest 객체를 만들기 위해 4개의 파라미터 필요
# 1st : 입력데이터,  2nd : 정답데이터
# 3rd : learning rate,  4th : iteration count
obj1 = LinearRegressionTest(x_data, t_data, 1e-5, 10001)

obj1.train()

LinearRegressionTest Object is created
Initial error value =  272.1053696047822 Initial W =  [[0.39554594]
 [0.94924778]
 [0.48519548]] 
 , b =  [0.04161918]
step =  0 error value =  112.46195312700404 W =  [[0.42094473]
 [0.97459593]
 [0.51161186]] , b =  [0.04181077]
step =  400 error value =  15.02356658868754 W =  [[0.44833759]
 [0.93277868]
 [0.64356154]] , b =  [0.04205359]
step =  800 error value =  12.364477637612067 W =  [[0.43777069]
 [0.86481718]
 [0.72024544]] , b =  [0.04190069]
step =  1200 error value =  10.499521051754567 W =  [[0.42849932]
 [0.80815483]
 [0.78462965]] , b =  [0.04166515]
step =  1600 error value =  9.191316546215482 W =  [[0.42035293]
 [0.76092917]
 [0.83869977]] , b =  [0.04136019]
step =  2000 error value =  8.273478043030256 W =  [[0.4131849 ]
 [0.72158324]
 [0.88411962]] , b =  [0.04099695]
step =  2400 error value =  7.629374453318411 W =  [[0.40686902]
 [0.68881561]
 [0.92228353]] , b =  [0.04058475]
step =  2800 error value =  7.177245778394409 

In [5]:
test_data = np.array([100, 98, 81])

obj1.predict(test_data) 

array([179.05634763])

### learning_rate = 1e-3,  반복횟수 10,000번 수행하는 obj2

In [6]:
# reset 하지 않은채 하이퍼파라미터 변경

obj2 = LinearRegressionTest(x_data, t_data, 1e-3, 10001)

obj2.train()

LinearRegressionTest Object is created
Initial error value =  719.2685782355427 Initial W =  [[0.74535756]
 [0.03991242]
 [0.89921848]] 
 , b =  [0.42328238]
step =  0 error value =  1028396.2458336486 W =  [[4.98426132]
 [4.3262106 ]
 [5.27405744]] , b =  [-1.58855105]
step =  400 error value =  4.936823732309998e+31 W =  [[1.05139060e+13]
 [3.25042048e+13]
 [4.34781583e+13]] , b =  [1.53142805e+08]
step =  800 error value =  4.936823732309998e+31 W =  [[1.05139060e+13]
 [3.25042048e+13]
 [4.34781583e+13]] , b =  [1.53142805e+08]
step =  1200 error value =  4.936823732309998e+31 W =  [[1.05139060e+13]
 [3.25042048e+13]
 [4.34781583e+13]] , b =  [1.53142805e+08]
step =  1600 error value =  4.936823732309998e+31 W =  [[1.05139060e+13]
 [3.25042048e+13]
 [4.34781583e+13]] , b =  [1.53142805e+08]
step =  2000 error value =  4.936823732309998e+31 W =  [[1.05139060e+13]
 [3.25042048e+13]
 [4.34781583e+13]] , b =  [1.53142805e+08]
step =  2400 error value =  4.936823732309998e+31 W =  [[1.05

In [7]:
test_data = np.array([100, 98, 81])

obj2.predict(test_data) 

array([7.75853365e+15])

### learning_rate = 1e-6,  반복횟수 10,000번 수행하는 obj3

In [8]:
# obj3 생성

obj3 = LinearRegressionTest(x_data, t_data, 1e-6, 10001)

obj3.train()

LinearRegressionTest Object is created
Initial error value =  1040.3314593348994 Initial W =  [[0.04398537]
 [0.66704495]
 [0.89780082]] 
 , b =  [0.67578578]
step =  0 error value =  961.0101833072055 W =  [[0.04912337]
 [0.67219683]
 [0.90308874]] , b =  [0.67584672]
step =  400 error value =  8.159007563173821 W =  [[0.17669052]
 [0.79474923]
 [1.03479898]] , b =  [0.67727695]
step =  800 error value =  8.101415167846344 W =  [[0.17839696]
 [0.79082662]
 [1.03697463]] , b =  [0.67720883]
step =  1200 error value =  8.045634905043217 W =  [[0.18008776]
 [0.78696546]
 [1.03910538]] , b =  [0.67714047]
step =  1600 error value =  7.991607410988173 W =  [[0.18176307]
 [0.78316478]
 [1.0411921 ]] , b =  [0.67707187]
step =  2000 error value =  7.939275317818733 W =  [[0.18342303]
 [0.77942358]
 [1.04323562]] , b =  [0.67700304]
step =  2400 error value =  7.88858318538691 W =  [[0.18506775]
 [0.77574087]
 [1.04523677]] , b =  [0.67693398]
step =  2800 error value =  7.839477435424962 W =

In [9]:
test_data = np.array([100, 98, 81])

obj3.predict(test_data) 

array([179.34593118])

### learning_rate = 1e-5,  반복횟수 8,000번 수행하는 obj4

In [10]:
# obj4 생성

obj4 = LinearRegressionTest(x_data, t_data, 1e-5, 8001)

obj4.train()

LinearRegressionTest Object is created
Initial error value =  3859.522758658984 Initial W =  [[0.04839035]
 [0.34522903]
 [0.84206034]] 
 , b =  [0.81446935]
step =  0 error value =  1431.035247642392 W =  [[0.14759425]
 [0.44493969]
 [0.94413579]] , b =  [0.8152147]
step =  400 error value =  6.354400277539583 W =  [[0.30649641]
 [0.590055  ]
 [1.10700923]] , b =  [0.8155944]
step =  800 error value =  6.328701709734579 W =  [[0.31106324]
 [0.58181022]
 [1.11063721]] , b =  [0.81481031]
step =  1200 error value =  6.309590210802766 W =  [[0.31521868]
 [0.57473279]
 [1.11352431]] , b =  [0.81402272]
step =  1600 error value =  6.295285831333713 W =  [[0.31899813]
 [0.56864927]
 [1.1158056 ]] , b =  [0.81323241]
step =  2000 error value =  6.284506663049473 W =  [[0.3224342 ]
 [0.56341292]
 [1.11759277]] , b =  [0.81244001]
step =  2400 error value =  6.276326059492162 W =  [[0.32555693]
 [0.55889943]
 [1.1189781 ]] , b =  [0.81164602]
step =  2800 error value =  6.270071452623943 W =  

In [11]:
test_data = np.array([100, 98, 81])

obj4.predict(test_data) 

array([178.78026376])

### learning_rate = 1e-5,  반복횟수 6,000번 수행하는 obj5

In [12]:
# obj5 생성

obj5 = LinearRegressionTest(x_data, t_data, 1e-5, 6001)

obj5.train()

LinearRegressionTest Object is created
Initial error value =  64.61266127043513 Initial W =  [[0.84898122]
 [0.50863367]
 [0.57322525]] 
 , b =  [0.82044779]
step =  0 error value =  33.04936214252628 W =  [[0.86015484]
 [0.51994674]
 [0.58504486]] , b =  [0.82053256]
step =  400 error value =  12.616105997249877 W =  [[0.82694436]
 [0.51787769]
 [0.67168057]] , b =  [0.820452]
step =  800 error value =  11.169175076072834 W =  [[0.7812032 ]
 [0.50310799]
 [0.73057111]] , b =  [0.820163]
step =  1200 error value =  10.0722487575273 W =  [[0.73996686]
 [0.49230754]
 [0.78120561]] , b =  [0.81980837]
step =  1600 error value =  9.235610684815152 W =  [[0.70278176]
 [0.48468102]
 [0.82480195]] , b =  [0.81939724]
step =  2000 error value =  8.593671900962798 W =  [[0.66924156]
 [0.47957681]
 [0.86239173]] , b =  [0.81893738]
step =  2400 error value =  8.098243093691172 W =  [[0.63898196]
 [0.47646228]
 [0.89484941]] , b =  [0.81843543]
step =  2800 error value =  7.713731059799472 W =  [

In [13]:
test_data = np.array([100, 98, 81])

obj5.predict(test_data) 

array([180.50380792])

### learning_rate = 1e-5,  반복횟수 20,000번 수행하는 obj6

In [14]:
# obj6 생성

obj6 = LinearRegressionTest(x_data, t_data, 1e-5, 20001)

obj6.train()

LinearRegressionTest Object is created
Initial error value =  4434.867268387614 Initial W =  [[0.15332245]
 [0.42919179]
 [0.6100074 ]] 
 , b =  [0.29707291]
step =  0 error value =  1644.83857623551 W =  [[0.25962112]
 [0.53601257]
 [0.71950358]] , b =  [0.29787281]
step =  400 error value =  7.5233807223007725 W =  [[0.41721749]
 [0.6717548 ]
 [0.92579074]] , b =  [0.29865608]
step =  800 error value =  7.118585325908246 W =  [[0.41070373]
 [0.64674498]
 [0.956567  ]] , b =  [0.2981572]
step =  1200 error value =  6.833876063339966 W =  [[0.40492193]
 [0.6259849 ]
 [0.98247943]] , b =  [0.29762508]
step =  1600 error value =  6.633497312217189 W =  [[0.39978413]
 [0.60876554]
 [1.00430627]] , b =  [0.29706499]
step =  2000 error value =  6.4923615725525154 W =  [[0.39521378]
 [0.594495  ]
 [1.02270034]] , b =  [0.29648133]
step =  2400 error value =  6.392862516468547 W =  [[0.39114405]
 [0.58267922]
 [1.03820928]] , b =  [0.29587782]
step =  2800 error value =  6.322640818809015 W =

In [15]:
test_data = np.array([100, 98, 81])

obj6.predict(test_data) 

array([178.86352902])